name:                assoclist
version:             0.1.0.0
github:              "martinprobson/assoclist"
license:             BSD3
author:              "Martin Robson"
maintainer:          "martinprobson@gmail.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Training/Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/martinprobson/assoclist#readme>

dependencies:
- base >= 4.7 && < 5
- tasty
- tasty-hunit

library:
  source-dirs: src

executables:
  assoclist-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assoclist

tests:
  assoclist-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assoclist
    - tasty
    - tasty-hunit
